import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Footer from "@/components/Footer";
import BlogAuth from "@/providers/BlogAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blogs Scroll",
  description: "Generated by Kasse Imad",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} dark:bg-gray-800 bg-gray-100 `}>
        <BlogAuth>
          <Navbar />
          {children}
          <Footer />
        </BlogAuth>
      </body>
    </html>
  );
}
